version: '3.8'

services:
  front:
    platform: linux/amd64 # M1 Macだと必要
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"

volumes:
  node_modules:
